### ISSUE TITLE
进游戏后一键喊话无法运行

### ISSUE THREAD

**Issue by lattefish** [ChenglongMa/LOLauncher#12]
大佬您好，因为B站无法上传图片我就在这跟您反馈，辛苦啦！

![问题图](https://github.com/user-attachments/assets/4f35d978-95e2-4b75-acdc-9bd383a9ef30)
![训练模式进程图](https://github.com/user-attachments/assets/05f0d7ca-acb0-4e29-8217-1db877ff9739)
![训练模式详细信息图](https://github.com/user-attachments/assets/fa7f433b-46f1-4bbd-9026-6e44a0e4590c)

**Comment by ChenglongMa** [comment]
感谢反馈！不过确实好奇怪，下面是我的进程列表：

![Snipaste_2024-07-26_23-11-18](https://github.com/user-attachments/assets/f89eb97a-120c-4112-a66b-ebb6dc04aaf9)

这里边有个 **"League of Legends.exe"**。

不确定为什么你的进程里没有这一项，我再查查看哈。

不过如果你能找到对应的进程名称的话可以手动修改一下配置文件：

文件路径是：`C:\Users\<你的用户名>\.lolauncher\config.json`
里边有一项是：

```json
{
"Process Name": "League of Legends.exe",
}
```

把这个改成你电脑上的进程名称就可以用了。

**Comment by lattefish** [comment]
![抱歉我之前好像没截图全](https://github.com/user-attachments/assets/9bbe2e95-377a-48dd-b601-02ea4b86820f)
![有这个进程](https://github.com/user-attachments/assets/ed91b96c-daa9-4867-8c89-c1db72fa0a36)
![然而问题依然存在](https://github.com/user-attachments/assets/ca02c259-3ed6-4d81-a0c5-d042cca0893e)


抱歉好像我之前没有截图截全，我有这些进程，然后进文件也检查了都是对的，我还尝试了用管理员方式打开但问题依然存在

**Comment by ChenglongMa** [comment]
多谢反馈！我再调试调试，换个检测进程的方法，非常感谢！

**Comment by lattefish** [comment]
谢谢大佬麻烦你了！多休息会儿别太肝啦

**Comment by ChenglongMa** [comment]
哈哈，多谢关心❤️

**Comment by ChenglongMa** [comment]
@lattefish 您好，

我试了几种方法，由于在我本机无法复现这一bug，所以还想请你帮帮忙🙏

如果可以的话，请按以下步骤测试：

1. 进入训练模式
2. 回到桌面，打开任意命令行工具
   *. 比如，在 `开始` 图标上右键 -> 选择 `Windows PowerShell` (Win 11 中请选择 `Terminal`)
    ![Snipaste_2024-08-02_10-46-31](https://github.com/user-attachments/assets/e507d1b9-4ca5-4a7b-a44f-a9809b0d2e2d)
3. 在命令行中执行以下命令并查看结果：
   ```bash
   tasklist /FI "ImageName eq League of Legends.exe" /FI "Status eq Running" /FO LIST
   ```
   如果出现以下结果，证明该方法可行：
   ```text
   Image Name:   League of Legends.exe
   PID:          <Random number>
   Session Name: Console
   Session#:     <Random number>
   Mem Usage:    <Random number> K
   ```
4. 如果以上命令不行，请执行以下命令并查看结果：
   ```bash
   tasklist /FI "ImageName eq League of Legends.exe" /FO LIST
   ```

如果还是不行我再想其他办法，谢谢！

**Comment by ChenglongMa** [comment]
[LOLauncher.zip](https://github.com/user-attachments/files/16489505/LOLauncher.zip)

@lattefish，

您好，根据测试，我尝试修复了这个bug，但还是由于我本地无法复现的问题，还需要您的帮助来测试一下。

如果您愿意的话，请下载这个回复中的更新版本然后试试 `一键喊话的功能`。

非常感谢！

**Comment by ChenglongMa** [comment]
客气客气！您先忙。我这不着急😊，非常非常感谢！

**Comment by lattefish** [comment]
您好抱歉让您久等啦，新版本正常了！一键喊话完全没有问题，然后我把PowerShell的截图发你，非常感谢！
![批注 2024-08-07 023704](https://github.com/user-attachments/assets/8d553477-49fd-4ca5-86bd-20c968f68fd7)

**Comment by ChenglongMa** [comment]
您太客气了，非常感谢您的帮助！有什么需要我改进的尽管跟我说😊
