### ISSUE TITLE
植入程序后首页网络链接

### ISSUE THREAD

**Issue by Jojo0121xxx** [ChenglongMa/LOLauncher#17]
首先感谢大佬的软件！终于听到中文版TvT
但是植入程序后发现游戏主页一直显示网络连接有问题，前面用英文版的时候一直没有出现过，想问一下大佬这个可能是哪块出现问题了呢
![image](https://github.com/user-attachments/assets/06be9d3c-2660-4482-9377-12c52f9e7d72)

**Comment by ChenglongMa** [comment]
感谢支持！

改成中文后首页的活动和广告就没法显示了，这个是拳头自己设置的，可能它想调用国服的活动页面，或者用了腾讯的网络代理去访问外服。

不过这个不影响使用，也不影响皮肤商城购买功能，我就一直这么用了😂

**Comment by Jojo0121xxx** [comment]
原来如此！那了解了，谢谢大佬^^

**Comment by ChenglongMa** [comment]
如果没有问题，我先把这个Issue关了，后续有任何我能帮到的地方请随时联系我😊
