### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by XinAnzzZ** [ChenglongMa/LOLauncher#3]
感谢分享，请问如何解决游戏内皮肤等页面仍然是英文的问题？如下：
![image](https://github.com/ChenglongMa/LOLauncher/assets/38024683/69f3372d-ceb2-49e5-a073-853b645fd544)
![image](https://github.com/ChenglongMa/LOLauncher/assets/38024683/cac09043-9c0b-4b75-bff7-99ae04d219f3)

**Comment by ChenglongMa** [comment]
不好意思，这个得看拳头那边怎么设置，我们没法自助更改。不过我看商城里进去是中文的

**Comment by ChenglongMa** [comment]
@XinAnzzZ 你好，这个问题我在新版本里解决了，但还有些瑕疵：

使用该软件打开游戏后，**需要先退出一次**，然后点 `更新`，再进入游戏就完全是中文了🤝
