### ISSUE TITLE
配置文件更新失败 无法启动

### ISSUE THREAD

**Issue by thiedx** [ChenglongMa/LOLauncher#7]
自动选择和手动选择均尝试无效。
![image](https://github.com/ChenglongMa/LOLauncher/assets/63764443/0e8e13cf-accf-4304-bb13-7e4b3722aaba)

**Comment by thiedx** [comment]
已解决 需要管理员运行

**Comment by ChenglongMa** [comment]
嗯嗯，解决了就好👌🏻

其实这是因为上个版本把配置文件改成只读了，这个版本我忘了兼容这个了。

你可以把C:\\ProgramData\\Riot Games\\Metadata\\league_of_legends.live\\league_of_legends.live.product_settings.yaml 这个文件的只读去掉。
这样也就不用管理员权限了。

多谢！
